# python main/eval/ddpm/generate_recons.py +dataset=celebahq/test \
#                         dataset.ddpm.data.root=\'/Users/charumathibadrinath/thesis-latent-spaces/test-data\' \
#                         dataset.ddpm.data.norm=True \
#                         dataset.ddpm.model.attn_resolutions=\'16,\' \
#                         dataset.ddpm.model.dropout=0.1 \
#                         dataset.ddpm.model.n_residual=2 \
#                         dataset.ddpm.model.dim_mults=\'1,1,2,2,4,4\' \
#                         dataset.ddpm.model.n_heads=8 \
#                         dataset.ddpm.evaluation.guidance_weight=0.0 \
#                         dataset.ddpm.evaluation.seed=3 \
#                         dataset.ddpm.evaluation.sample_prefix='cpu' \
#                         dataset.ddpm.evaluation.device=\'cpu\' \
#                         dataset.ddpm.evaluation.save_mode='image' \
#                         dataset.ddpm.evaluation.chkpt_path=\'~/Downloads/diffvae_chq256_form1_loss=0.0361.ckpt\' \
#                         dataset.ddpm.evaluation.type='form1' \
#                         dataset.ddpm.evaluation.resample_strategy='spaced' \
#                         dataset.ddpm.evaluation.skip_strategy='quad' \
#                         dataset.ddpm.evaluation.sample_method='ddim' \
#                         dataset.ddpm.evaluation.sample_from='target' \
#                         dataset.ddpm.evaluation.temp=0.8 \
#                         dataset.ddpm.evaluation.batch_size=1 \
#                         dataset.ddpm.evaluation.save_path=\'\' \
#                         dataset.ddpm.evaluation.z_cond=False \
#                         dataset.ddpm.evaluation.n_samples=5 \
#                         dataset.ddpm.evaluation.n_steps=100 \
#                         dataset.ddpm.evaluation.save_vae=True \
#                         dataset.ddpm.evaluation.workers=1 \
#                         dataset.vae.evaluation.chkpt_path=\'~/Downloads/vae_chq256_alpha=1.0_loss=0.0000.ckpt\'

python main/eval/ddpm/generate_recons.py +dataset='celeba64/test' \
                        dataset.ddpm.data.root=\'/Users/charumathibadrinath/thesis-latent-spaces/test-data\' \
                        dataset.ddpm.data.norm=True \
                        dataset.ddpm.data.hflip=False \
                        dataset.ddpm.model.attn_resolutions=\'16,\' \
                        dataset.ddpm.model.dropout=0.1 \
                        dataset.ddpm.model.n_residual=2 \
                        dataset.ddpm.model.dim_mults=\'1,2,2,2,4\' \
                        dataset.ddpm.model.n_heads=1 \
                        dataset.ddpm.evaluation.guidance_weight=0.0 \
                        dataset.ddpm.evaluation.seed=0 \
                        dataset.ddpm.evaluation.sample_prefix='cpu' \
                        dataset.ddpm.evaluation.device=\'cpu\' \
                        dataset.ddpm.evaluation.save_mode='image' \
                        dataset.ddpm.evaluation.chkpt_path=\'~/thesis-latent-spaces/pickles/vae-ddpm-celeba.ckpt\' \
                        dataset.ddpm.evaluation.type='form2' \
                        dataset.ddpm.evaluation.resample_strategy='spaced' \
                        dataset.ddpm.evaluation.skip_strategy='quad' \
                        dataset.ddpm.evaluation.sample_method='ddim' \
                        dataset.ddpm.evaluation.sample_from='target' \
                        dataset.ddpm.evaluation.temp=0.0 \
                        dataset.ddpm.evaluation.batch_size=1 \
                        dataset.ddpm.evaluation.save_path=\'\' \
                        dataset.ddpm.evaluation.z_cond=False \
                        dataset.ddpm.evaluation.n_samples=5 \
                        dataset.ddpm.evaluation.n_steps=20 \
                        dataset.ddpm.evaluation.save_vae=True \
                        dataset.ddpm.evaluation.workers=1 \
                        dataset.vae.evaluation.chkpt_path=\'~/thesis-latent-spaces/pickles/vae-celeba.ckpt\'

# python main/eval/ddpm/generate_recons.py +dataset=cifar10/test \
#                         dataset.ddpm.data.root=\'/Users/charumathibadrinath/thesis-latent-spaces/gen\' \
#                         dataset.ddpm.data.norm=True \
#                         dataset.ddpm.model.attn_resolutions=\'16,\' \
#                         dataset.ddpm.model.dropout=0.1 \
#                         dataset.ddpm.model.n_heads=1 \
#                         dataset.ddpm.model.dim_mults=\'1,2,2,2\' \
#                         dataset.ddpm.evaluation.seed=0 \
#                         dataset.ddpm.evaluation.sample_prefix='cpu' \
#                         dataset.ddpm.evaluation.device=\'cpu\' \
#                         dataset.ddpm.evaluation.save_mode='image' \
#                         dataset.ddpm.evaluation.chkpt_path=\'~/thesis-latent-spaces/pickles/vae-ddpm-cifar.ckpt\' \
#                         dataset.ddpm.evaluation.type='form2' \
#                         dataset.ddpm.evaluation.variance='fixedsmall' \
#                         dataset.ddpm.evaluation.resample_strategy='spaced' \
#                         dataset.ddpm.evaluation.skip_strategy='quad' \
#                         dataset.ddpm.evaluation.sample_method='ddim' \
#                         dataset.ddpm.evaluation.sample_from='target' \
#                         dataset.ddpm.evaluation.batch_size=1 \
#                         dataset.ddpm.evaluation.save_path=\'\' \
#                         dataset.ddpm.evaluation.n_samples=10 \
#                         dataset.ddpm.evaluation.n_steps=20 \
#                         dataset.ddpm.evaluation.workers=1 \
#                         dataset.vae.evaluation.chkpt_path=\'~/thesis-latent-spaces/pickles/vae-cifar.ckpt\'